name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform-validation:
    name: Terraform validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-azure-lab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate
  react-build:
    name: React build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "fakhar-abbas-react"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

  deploy-to-aci:
    name: Deploy React app to Container Instance
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [terraform-validation, react-build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR
        run: |
          az acr build \
            --registry acraz104lab08 \
            --resource-group rg-security \
            --image fakhar-abbas-react:${{ github.sha }} \
            --image fakhar-abbas-react:latest \
            fakhar-abbas-react
          
      - name: Remove existing container instance (if any)
        run: |
          az container delete \
            --resource-group rg-security \
            --name fakhar-abbas-react-aci \
            --yes || true

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group rg-security \
            --name fakhar-abbas-react-aci \
            --image acraz104lab08.azurecr.io/fakhar-abbas-react:${{ github.sha }} \
            --assign-identity /subscriptions/adc9f320-e56e-45b1-845e-c73484745fc8/resourcegroups/rg-az104-lab07/providers/Microsoft.ManagedIdentity/userAssignedIdentities/az104lab07-mi \
            --acr-identity /subscriptions/adc9f320-e56e-45b1-845e-c73484745fc8/resourcegroups/rg-az104-lab07/providers/Microsoft.ManagedIdentity/userAssignedIdentities/az104lab07-mi \
            --ports 80 \
            --cpu 1 \
            --memory 1 \
            --os-type Linux \
            --dns-name-label fakhar-abbas-react \
            --location eastus